/**
 * CasaOS Local Storage API
 * <picture>     <source media=\"(prefers-color-scheme: dark)\" srcset=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_dark_night_800px.png\">     <source media=\"(prefers-color-scheme: light)\" srcset=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_twilight_blue_800px.png\">     <img alt=\"CasaOS\" src=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_twilight_blue_800px.png\"> </picture>  CasaOS Local Storage service manages local storage including disks, partitions and mounting points.  This API allows interacting with the service to conduct such management.  For issues and discussions, please visit the [GitHub repository](https://github.com/IceWhaleTech/CasaOS) or join [our Discord](https://discord.gg/knqAbbBbeX).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BaseResponse from './model/BaseResponse';
import GetMounts200Response from './model/GetMounts200Response';
import GetMounts200ResponseAllOf from './model/GetMounts200ResponseAllOf';
import Mount from './model/Mount';
import UpdateMount200Response from './model/UpdateMount200Response';
import UpdateMount200ResponseAllOf from './model/UpdateMount200ResponseAllOf';
import UpdateMount400Response from './model/UpdateMount400Response';
import MountMethodsApi from './api/MountMethodsApi';


/**
* &lt;picture&gt;     &lt;source media&#x3D;\&quot;(prefers-color-scheme: dark)\&quot; srcset&#x3D;\&quot;https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_dark_night_800px.png\&quot;&gt;     &lt;source media&#x3D;\&quot;(prefers-color-scheme: light)\&quot; srcset&#x3D;\&quot;https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_twilight_blue_800px.png\&quot;&gt;     &lt;img alt&#x3D;\&quot;CasaOS\&quot; src&#x3D;\&quot;https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_twilight_blue_800px.png\&quot;&gt; &lt;/picture&gt;  CasaOS Local Storage service manages local storage including disks, partitions and mounting points.  This API allows interacting with the service to conduct such management.  For issues and discussions, please visit the [GitHub repository](https://github.com/IceWhaleTech/CasaOS) or join [our Discord](https://discord.gg/knqAbbBbeX)..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AMD = require('index'); // See note below*.
* var xxxSvc = new AMD.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AMD.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AMD.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AMD.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BaseResponse model constructor.
     * @property {module:model/BaseResponse}
     */
    BaseResponse,

    /**
     * The GetMounts200Response model constructor.
     * @property {module:model/GetMounts200Response}
     */
    GetMounts200Response,

    /**
     * The GetMounts200ResponseAllOf model constructor.
     * @property {module:model/GetMounts200ResponseAllOf}
     */
    GetMounts200ResponseAllOf,

    /**
     * The Mount model constructor.
     * @property {module:model/Mount}
     */
    Mount,

    /**
     * The UpdateMount200Response model constructor.
     * @property {module:model/UpdateMount200Response}
     */
    UpdateMount200Response,

    /**
     * The UpdateMount200ResponseAllOf model constructor.
     * @property {module:model/UpdateMount200ResponseAllOf}
     */
    UpdateMount200ResponseAllOf,

    /**
     * The UpdateMount400Response model constructor.
     * @property {module:model/UpdateMount400Response}
     */
    UpdateMount400Response,

    /**
    * The MountMethodsApi service constructor.
    * @property {module:api/MountMethodsApi}
    */
    MountMethodsApi
};
