/**
 * CasaOS Local Storage API
 * <picture>     <source media=\"(prefers-color-scheme: dark)\" srcset=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_dark_night_800px.png\">     <source media=\"(prefers-color-scheme: light)\" srcset=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_twilight_blue_800px.png\">     <img alt=\"CasaOS\" src=\"https://raw.githubusercontent.com/IceWhaleTech/logo/main/casaos/casaos_banner_twilight_blue_800px.png\"> </picture>  CasaOS Local Storage service manages local storage including disks, partitions and mounting points.  This API allows interacting with the service to conduct such management.  For issues and discussions, please visit the [GitHub repository](https://github.com/IceWhaleTech/CasaOS) or join [our Discord](https://discord.gg/knqAbbBbeX).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CasaOsLocalStorageApi);
  }
}(this, function(expect, CasaOsLocalStorageApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CasaOsLocalStorageApi.Mount();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Mount', function() {
    it('should create an instance of Mount', function() {
      // uncomment below and update the code to test Mount
      //var instance = new CasaOsLocalStorageApi.Mount();
      //expect(instance).to.be.a(CasaOsLocalStorageApi.Mount);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CasaOsLocalStorageApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property mountPoint (base name: "mount_point")', function() {
      // uncomment below and update the code to test the property mountPoint
      //var instance = new CasaOsLocalStorageApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property fstype (base name: "fstype")', function() {
      // uncomment below and update the code to test the property fstype
      //var instance = new CasaOsLocalStorageApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new CasaOsLocalStorageApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instance = new CasaOsLocalStorageApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property persist (base name: "persist")', function() {
      // uncomment below and update the code to test the property persist
      //var instance = new CasaOsLocalStorageApi.Mount();
      //expect(instance).to.be();
    });

    it('should have the property extended (base name: "extended")', function() {
      // uncomment below and update the code to test the property extended
      //var instance = new CasaOsLocalStorageApi.Mount();
      //expect(instance).to.be();
    });

  });

}));
