name: IceWhaleTech Node.js prerelease CI

on:
  push:
    tags:
      - v*.*.*
jobs:
  release:

    runs-on: ubuntu-latest
    if: github.repository == 'IceWhaleTech/CasaOS-UI'
    strategy:
      matrix:
        node-version: [ 16.x ]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: '使用 Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: '缓存 Cache'
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - run: yarn install
      - run: yarn build
      - run: |
          cp ./build/sysroot/var/lib/casaos/www/img/wallpaper0*.jpg ./build/sysroot/var/lib/casaos/www/ui/img/
          tar -zcvf linux-all-casaos-${{ env.VERSION }}.tar.gz build
      - name: '更新 Update release'
        uses: zhanghengxin/git-release-private@ice
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          gzip: false
          prerelease: true
          tag: ${{ steps.get_version.outputs.VERSION }}
          files: ./linux-all-casaos-${{ steps.get_version.outputs.VERSION }}.tar.gz
      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-shanghai
          bucket: casaos
          assets: |
            ./linux-all-casaos-${{ steps.get_version.outputs.VERSION }}.tar.gz:/CasaOS-UI/releases/download/${{ steps.get_version.outputs.VERSION }}/linux-all-casaos-${{ steps.get_version.outputs.VERSION }}.tar.gz

